version: 1
eventstore1:
  url: http://localhost:8090/location/weatherForecast
eventstore2:
  url: http://localhost:8090/location/miscWeather
events:
  hostname: kafka-acit3855-lab6a.eastus2.cloudapp.azure.com
  port: 9092
  topic: events
connection:
  max_retries: 60
  sleep_time: 5
