version: 1
datastore:
  filename: /data/data.json
scheduler:
  period_sec: 5
eventstore1:
  url: http://kafka-acit3855-lab6a.eastus2.cloudapp.azure.com/storage/location/weatherForecast
eventstore2:
  url: http://kafka-acit3855-lab6a.eastus2.cloudapp.azure.com/storage/location/miscWeather
